server:
  port: 8080
  context-path: /api
zuul:
  sensitiveHeaders:
  routes:
    user-service:
      path: /users/**
      url: http://127.0.0.1:8081
      strip-prefix: false
    login-service:
      path: /login
      url: http://127.0.0.1:8081
      strip-prefix: false
    todo-service:
      path: /todos/**
      url: http://127.0.0.1:8082
      strip-prefix: false
    task-service:
      path: /tasks/**
      url: http://127.0.0.1:8082
      strip-prefix: false

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: TRACE

private:
  password: zhangtian